### PR TITLE
Merge master into devops

### PR DESCRIPTION
**Pull request by IanKBovard**
Master merged into devops.

### CODE REVIEW

**Comment by mrebb** [comment]
@IanKBovard Looks good on deployment architecture wise. Looks like high scores slide and upcoming sessions are smooshed inside carousel.

**Comment by IanKBovard** [comment]
> @IanKBovard Looks good on deployment architecture wise. Looks like high scores slide and upcoming sessions are smooshed inside carousel.

are you talking about when the component loads?

**Comment by IanKBovard** [comment]
there are a few things i'd like to fix, but i wanted to get this branch updated first.

**Comment by mrebb** [comment]
> > @IanKBovard Looks good on deployment architecture wise. Looks like high scores slide and upcoming sessions are smooshed inside carousel.
> 
> are you talking about when the component loads?

Please refer below screenshots:
Screen Shot 2019-06-13 at 12 31 19 AM
Screen Shot 2019-06-13 at 12 32 24 AM

**Comment by halocline** [comment]
> > > @IanKBovard Looks good on deployment architecture wise. Looks like high scores slide and upcoming sessions are smooshed inside carousel.
> > 
> > 
> > are you talking about when the component loads?
> 
> Please refer below screenshots:
> Screen Shot 2019-06-13 at 12 31 19 AM
> Screen Shot 2019-06-13 at 12 32 24 AM

@IanKBovard @mrebb -- Ian, I agree. Let's get the branch updated first. We can then address the refinements to the visual presentation.

**Comment by IanKBovard** [comment]
if looks like grommet isnt installed

**Comment by IanKBovard** [comment]
the theme and the components aren't coming through

**Pull request merged**
